TARGET = modbus_vbat
SRCS_C = main.c
SDK_EXTRA_C = $(SDK)/Peripheral/src/ch32v20x_adc.c \
              $(SDK)/Peripheral/src/ch32v20x_flash.c \
              $(SDK)/Peripheral/src/ch32v20x_iwdg.c
include ../../common/Makefile.common
